### ISSUE TITLE
Model 1

### ISSUE THREAD

**Issue by mohit-surana** [rohinikapoor/organizational-roles#5]
Design the first model (s_rep + r_rep -> email_pred, email -> email_rep, error = email_rep - email_pred) in model1.py (https://github.com/rohinikapoor/organizational-roles/blob/master/code/model1.py)

This contains placeholders for:
1) save - save model, associated data structures and possibly seeds for training and optimizer state
2) load - load the above mentioned items in a way that training can be "paused" and "resumed"
3) train - given a list of (sender, recipient, email_body), train a model that generates the expected email representation. also learn a good sender and recipient representation
4) get_repr - retrieve a given user's vector representation

Print the objective function value as part of the training process to assess performance.

**Comment by mudit1990** [comment]
Model1 and a new variant model3 code are up. In the process of debugging them to get better performance
